-- Satin Road – demo data for the presentation
-- Runs once, right after 01-init.sql, when the database volume is empty.
-- Reset everything:  docker compose down -v && docker compose up --build
--
-- All demo accounts use the password:  demo1234
-- (the admin account admin / admin123 is created by the API on startup)

-- BCrypt hashes are generated by Postgres itself (pgcrypto, "bf" = bcrypt),
-- BCrypt.Net in the API can verify them.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------- 1. Users ----------
INSERT INTO users (username, password_hash, role) VALUES
    ('darknet_dave', crypt('demo1234', gen_salt('bf', 11)), 'User'),  -- featured vendor: 150 sales
    ('silk_sarah',   crypt('demo1234', gen_salt('bf', 11)), 'User'),  -- featured vendor: 120 sales
    ('shady_steve',  crypt('demo1234', gen_salt('bf', 11)), 'User'),  -- small vendor – use him for the FBI raid demo
    ('buyer_bob',    crypt('demo1234', gen_salt('bf', 11)), 'User'),  -- 11 orders at darknet_dave → his NEXT order there gets −20 %
    ('buyer_alice',  crypt('demo1234', gen_salt('bf', 11)), 'User');  -- loyal customer of both featured vendors

-- ---------- 2. Listings ----------
INSERT INTO listings (vendor_id, category_id, title, description, price, stock)
SELECT u.id, c.id, v.title, v.description, v.price, v.stock
FROM (VALUES
    ('darknet_dave', 'Counterfeits',     'Fake Rolex Submariner',                  'Ticks almost like the real one. Almost.',                 89.99,  500),
    ('darknet_dave', 'Stolen Artifacts', 'Mona Lisa (definitely the original)',    'Slight smile, slight provenance issues.',               4999.00,    3),
    ('darknet_dave', 'Drugs',            'Premium Oregano – totally not suspicious','Hand-picked in Italy. Great on pizza.',                    12.50,  200),
    ('silk_sarah',   'Weapons',          'Rubber Chicken Launcher',                'Range 30 m. Squeaks on impact.',                          149.00,   40),
    ('silk_sarah',   'Counterfeits',     'Monopoly Money Bundle (very convincing)','Accepted at most board game nights.',                      25.00,  300),
    ('silk_sarah',   'Drugs',            'Grandma''s Secret Catnip',               'Your cat will never look at you the same way again.',      9.99,  120),
    ('shady_steve',  'Stolen Artifacts', 'Medieval Sword (slightly borrowed)',     'The museum has not noticed yet.',                         349.00,    2),
    ('shady_steve',  'Weapons',          'Water Pistol Deluxe 3000',               'Holds 2 litres. Summer is coming.',                        19.99,   25),
    ('shady_steve',  'Counterfeits',     'Designer Handbag – Gucchi',              'Spot the difference. We dare you.',                        59.00,   10)
) AS v(vendor, category, title, description, price, stock)
JOIN users u      ON u.username = v.vendor
JOIN categories c ON c.name = v.category;

-- ---------- 3. Orders ----------
-- Rule from OrderService: a buyer with MORE than 10 previous orders at a vendor gets −20 %,
-- so in a series of orders the 12th one (g > 11) is the first discounted one.

-- buyer_alice → darknet_dave: 139 orders
INSERT INTO orders (buyer_id, vendor_id, listing_id, quantity, unit_price, discount_applied, total, created_at)
SELECT b.id, l.vendor_id, l.id, 1, l.price,
       g > 11,
       ROUND(l.price * CASE WHEN g > 11 THEN 0.8 ELSE 1 END, 2),
       now() - (400 - g) * interval '1 hour'
FROM generate_series(1, 139) AS g,
     (SELECT id FROM users WHERE username = 'buyer_alice') AS b,
     (SELECT id, vendor_id, price FROM listings WHERE title = 'Fake Rolex Submariner') AS l;

-- buyer_bob → darknet_dave: 11 orders (none discounted yet)  ⇒  darknet_dave = 139 + 11 = 150 sales
INSERT INTO orders (buyer_id, vendor_id, listing_id, quantity, unit_price, discount_applied, total, created_at)
SELECT b.id, l.vendor_id, l.id, 1, l.price, FALSE, l.price,
       now() - (100 - g) * interval '1 hour'
FROM generate_series(1, 11) AS g,
     (SELECT id FROM users WHERE username = 'buyer_bob') AS b,
     (SELECT id, vendor_id, price FROM listings WHERE title = 'Premium Oregano – totally not suspicious') AS l;

-- buyer_alice → silk_sarah: 120 orders
INSERT INTO orders (buyer_id, vendor_id, listing_id, quantity, unit_price, discount_applied, total, created_at)
SELECT b.id, l.vendor_id, l.id, 1, l.price,
       g > 11,
       ROUND(l.price * CASE WHEN g > 11 THEN 0.8 ELSE 1 END, 2),
       now() - (300 - g) * interval '1 hour'
FROM generate_series(1, 120) AS g,
     (SELECT id FROM users WHERE username = 'buyer_alice') AS b,
     (SELECT id, vendor_id, price FROM listings WHERE title = 'Monopoly Money Bundle (very convincing)') AS l;

-- buyer_bob → shady_steve: 5 orders (not featured)
INSERT INTO orders (buyer_id, vendor_id, listing_id, quantity, unit_price, discount_applied, total, created_at)
SELECT b.id, l.vendor_id, l.id, 1, l.price, FALSE, l.price,
       now() - (50 - g) * interval '1 hour'
FROM generate_series(1, 5) AS g,
     (SELECT id FROM users WHERE username = 'buyer_bob') AS b,
     (SELECT id, vendor_id, price FROM listings WHERE title = 'Water Pistol Deluxe 3000') AS l;
